### PR TITLE
Fixed issues Title exceeding document boundaries

### LINKED ISSUE #46: Title exceeding document boundaries
This is my spec file:
`line ('for', '(', loop (opt (opt('Typ'), '/Bezeichner', '=', '/Anweisung'), ","), ';', opt ('/boolscher Ausdruck'), ';', opt (loop ('/Anweisung', ','), ), ')', '/Anweisung')
`
and this the command to produce an PNG with title (the problem exists with SVG output, too:)
`./jsyntrax/target/appassembler/bin/syntrax -title "klassische for-Loop (jsyntrax, cmd-2)" kl-for-loop2.spec -o kl-for-loop2.png`

and this the resulting image: 
kl-for-loop2

The title starts left of the document and is therefore cut off. I did not change the .ini-files.

### PR DESCRIPTION
**Pull request by AlexandrKopertehov**
Fix #46

### CODE REVIEW

File: jsyntrax/src/main/java/org/atpfivt/jsyntrax/generators/elements/BubbleElementBase.java [hunk 1]
```diff
@@ -31,6 +31,24 @@ void addXMLText(StringBuilder sb, StyleConfig style) {
         int y1 = super.getEnd().s;
 
         int x = (x0 + x1) / 2;
+
+        if (TitleElement.class.equals(getClass())) {
```
Comment (inponomarev) [inline jsyntrax/src/main/java/org/atpfivt/jsyntrax/generators/elements/BubbleElementBase.java:35]: why not `this instanceof TitleElement`?

**Review by inponomarev — CHANGES_REQUESTED** [review]
Please also add a test based on the original example from the issue
